### ISSUE TITLE
Crash when loading a map

### ISSUE THREAD

**Issue by crlotwhite** [heria-zone/reignited-hud#4]
Hello,
Thanks to your mod, my HUD has become beautiful. 
However, I found a critical bug.

When a player tries to ride a non-tamed camel, the game crashes and I cannot access my world. 
After disabling Reignited-Hub, I was finally able to access my world again.

I believe there is a bug in the code related to getting information about riding.

Thank you, and have a nice day.

-- my environment --
fabric: latest
mc: 1.20.1

[latest.log](https://github.com/user-attachments/files/16245288/latest.log)

**Comment by AnthemV** [comment]
I was able to replicate this with the latest version of Reignited HUD on a minimal 1.20.1 install. Normal horses work as expected, but attempting to ride a llama, skeleton horse, or zombie horse will crash the game when Mount Information is enabled in the HUD config. Notably, this crash _does not_ occur when Mount Information is instead disabled. Unfortunately, this isn't an option on fabric due to #5.  

This would appear to be the relevant error:
```	
java.lang.ClassCastException: class net.minecraft.class_1501 cannot be cast to class net.minecraft.class_1498 (net.minecraft.class_1501 and net.minecraft.class_1498 are in unnamed module of loader net.fabricmc.loader.impl.launch.knot.KnotClassLoader @35fb3008)
	at net.msymbios.reignitedhud.gui.GuiWidget.getMountInfo(GuiWidget.java:260)
	at net.msymbios.reignitedhud.gui.GuiWidget.renderOverlay(GuiWidget.java:75)
	at net.fabricmc.fabric.api.client.rendering.v1.HudRenderCallback.lambda$static$0(HudRenderCallback.java:27)
	at net.minecraft.client.gui.hud.InGameHud.handler$zio000$fabric-rendering-v1$render(InGameHud.java:1386)
	at net.minecraft.client.gui.hud.InGameHud.render(InGameHud.java:370)
	at net.minecraft.client.render.GameRenderer.render(GameRenderer.java:926)
	at net.minecraft.client.MinecraftClient.render(MinecraftClient.java:1219)
	at net.minecraft.client.MinecraftClient.run(MinecraftClient.java:802)
	at net.minecraft.client.main.Main.main(Main.java:250)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:480)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
	at org.prismlauncher.launcher.impl.StandardLauncher.launch(StandardLauncher.java:100)
	at org.prismlauncher.EntryPoint.listen(EntryPoint.java:129)
	at org.prismlauncher.EntryPoint.main(EntryPoint.java:70)
```


[Full Crash Report](https://mclo.gs/Pl3FT7q)

#### Mods Installed
- Reignited HUD
- Fabric API
- Mod Menu
- ClothConfig
- YetAnotherConfigLib

**Comment by s2erge** [comment]
Thank you for the detailed issue, I will be working on the next update for Reignited HUD, and hopefully, I will solve most if not all the issues.
